FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Setting PYTHONPATH so `app.config` imports work
ENV PYTHONPATH=/app

# Run the normalizer worker
CMD ["python", "services/normalization/worker.py"]
